-- Estructura de tabla para la tabla `app`
--

CREATE TABLE `app` (
  `id` bigint(20) NOT NULL,
  `category` enum('DESIGN','DEVELOPMENT','ENTERTAINMENT','GAME','MUSIC','PRODUCTIVITY') NOT NULL,
  `download_url` text NOT NULL,
  `image_url` text NOT NULL,
  `name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `app`
--

INSERT INTO `app` (`id`, `category`, `download_url`, `image_url`, `name`) VALUES
(1, 'DEVELOPMENT', 'https://code.visualstudio.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/visualstudiocode.svg', 'Visual Studio Code'),
(2, 'DEVELOPMENT', 'https://www.docker.com/products/docker-desktop/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/docker.svg', 'Docker Desktop'),
(3, 'DEVELOPMENT', 'https://www.postman.com/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/postman.svg', 'Postman'),
(4, 'DEVELOPMENT', 'https://desktop.github.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/github.svg', 'GitHub Desktop'),
(5, 'DEVELOPMENT', 'https://www.jetbrains.com/idea/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/intellijidea.svg', 'IntelliJ IDEA'),
(6, 'PRODUCTIVITY', 'https://slack.com/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/slack.svg', 'Slack'),
(7, 'PRODUCTIVITY', 'https://www.notion.so/desktop', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/notion.svg', 'Notion'),
(8, 'PRODUCTIVITY', 'https://trello.com/platforms', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/trello.svg', 'Trello'),
(9, 'PRODUCTIVITY', 'https://evernote.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/evernote.svg', 'Evernote'),
(10, 'PRODUCTIVITY', 'https://todoist.com/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/todoist.svg', 'Todoist'),
(11, 'DESIGN', 'https://www.figma.com/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/figma.svg', 'Figma'),
(12, 'DESIGN', 'https://www.canva.com/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/canva.svg', 'Canva'),
(13, 'DESIGN', 'https://www.blender.org/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/blender.svg', 'Blender'),
(14, 'DESIGN', 'https://www.gimp.org/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/gimp.svg', 'GIMP'),
(15, 'DESIGN', 'https://inkscape.org/release/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/inkscape.svg', 'Inkscape'),
(16, 'DESIGN', 'https://www.adobe.com/products/photoshop.html', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/adobephotoshop.svg', 'Adobe Photoshop'),
(17, 'MUSIC', 'https://www.spotify.com/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/spotify.svg', 'Spotify'),
(18, 'MUSIC', 'https://www.apple.com/apple-music/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/applemusic.svg', 'Apple Music'),
(19, 'MUSIC', 'https://www.videolan.org/vlc/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/vlcmediaplayer.svg', 'VLC Media Player'),
(20, 'ENTERTAINMENT', 'https://www.netflix.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/netflix.svg', 'Netflix'),
(21, 'ENTERTAINMENT', 'https://www.max.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/hbo.svg', 'HBO'),
(22, 'ENTERTAINMENT', 'https://obsproject.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/obsstudio.svg', 'OBS Studio'),
(23, 'GAME', 'https://store.steampowered.com/about/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/steam.svg', 'Steam'),
(24, 'GAME', 'https://discord.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/discord.svg', 'Discord'),
(25, 'GAME', 'https://store.epicgames.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/epicgames.svg', 'Epic Games Launcher'),
(26, 'GAME', 'https://www.minecraft.net/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/minecraft.svg', 'Minecraft'),
(27, 'GAME', 'https://www.leagueoflegends.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/leagueoflegends.svg', 'League of Legends'),
(28, 'GAME', 'https://playvalorant.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/valorant.svg', 'Valorant'),
(29, 'DEVELOPMENT', 'https://git-scm.com/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/git.svg', 'Git'),
(30, 'DEVELOPMENT', 'https://nodejs.org/en/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/nodedotjs.svg', 'Node.js'),
(31, 'DEVELOPMENT', 'https://www.sublimetext.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/sublimetext.svg', 'Sublime Text'),
(32, 'DEVELOPMENT', 'https://developer.android.com/studio', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/androidstudio.svg', 'Android Studio'),
(33, 'DEVELOPMENT', 'https://visualstudio.microsoft.com/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/visualstudio.svg', 'Visual Studio'),
(34, 'DEVELOPMENT', 'https://filezilla-project.org/download.php', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/filezilla.svg', 'FileZilla'),
(35, 'DEVELOPMENT', 'https://insomnia.rest/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/insomnia.svg', 'Insomnia'),
(36, 'DEVELOPMENT', 'https://www.eclipse.org/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/eclipseide.svg', 'Eclipse IDE'),
(37, 'PRODUCTIVITY', 'https://zoom.us/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/zoom.svg', 'Zoom'),
(38, 'PRODUCTIVITY', 'https://www.microsoft.com/en-us/microsoft-teams/download-app', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/microsoftteams.svg', 'Microsoft Teams'),
(39, 'PRODUCTIVITY', 'https://www.dropbox.com/install', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/dropbox.svg', 'Dropbox'),
(40, 'PRODUCTIVITY', 'https://www.google.com/drive/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/googledrive.svg', 'Google Drive'),
(41, 'PRODUCTIVITY', 'https://www.grammarly.com/desktop', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/grammarly.svg', 'Grammarly'),
(42, 'PRODUCTIVITY', 'https://www.lastpass.com/misc/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/lastpass.svg', 'LastPass'),
(43, 'PRODUCTIVITY', 'https://asana.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/asana.svg', 'Asana'),
(44, 'PRODUCTIVITY', 'https://clickup.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/clickup.svg', 'ClickUp'),
(45, 'DESIGN', 'https://www.adobe.com/products/illustrator.html', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/adobeillustrator.svg', 'Adobe Illustrator'),
(46, 'DESIGN', 'https://www.adobe.com/products/premiere.html', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/adobepremierepro.svg', 'Adobe Premiere Pro'),
(47, 'DESIGN', 'https://www.adobe.com/products/aftereffects.html', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/adobeaftereffects.svg', 'Adobe After Effects'),
(48, 'DESIGN', 'https://www.sketch.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/sketch.svg', 'Sketch'),
(49, 'DESIGN', 'https://krita.org/en/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/krita.svg', 'Krita'),
(50, 'DESIGN', 'https://www.autodesk.com/products/autocad/overview', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/autodesk.svg', 'Autodesk AutoCAD'),
(51, 'MUSIC', 'https://music.youtube.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/youtubemusic.svg', 'YouTube Music'),
(52, 'MUSIC', 'https://www.amazon.com/music/unlimited/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/amazonmusic.svg', 'Amazon Music'),
(53, 'MUSIC', 'https://soundcloud.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/soundcloud.svg', 'SoundCloud'),
(54, 'MUSIC', 'https://tidal.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/tidal.svg', 'Tidal'),
(55, 'MUSIC', 'https://www.pandora.com/desktop', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/pandora.svg', 'Pandora'),
(56, 'MUSIC', 'https://www.deezer.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/deezer.svg', 'Deezer'),
(57, 'ENTERTAINMENT', 'https://www.youtube.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/youtube.svg', 'YouTube'),
(58, 'ENTERTAINMENT', 'https://www.twitch.tv/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/twitch.svg', 'Twitch'),
(59, 'ENTERTAINMENT', 'https://www.plex.tv/media-server-downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/plex.svg', 'Plex'),
(60, 'ENTERTAINMENT', 'https://kodi.tv/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/kodi.svg', 'Kodi'),
(61, 'ENTERTAINMENT', 'https://www.hulu.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/hulu.svg', 'Hulu'),
(62, 'ENTERTAINMENT', 'https://www.amazon.com/gp/video/storefront/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/amazonprime.svg', 'Prime Video'),
(64, 'GAME', 'https://www.gog.com/galaxy', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/gogdotcom.svg', 'GOG Galaxy'),
(65, 'GAME', 'https://www.blizzard.com/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/battledotnet.svg', 'Battle.net'),
(66, 'GAME', 'https://unity.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/unity.svg', 'Unity'),
(67, 'GAME', 'https://www.unrealengine.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/unrealengine.svg', 'Unreal Engine'),
(68, 'GAME', 'https://www.fortnite.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/fortnite.svg', 'Fortnite'),
(69, 'GAME', 'https://www.roblox.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/roblox.svg', 'Roblox'),
(70, 'GAME', 'https://teamspeak.com/en/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/teamspeak.svg', 'TeamSpeak'),
(72, 'DEVELOPMENT', 'https://www.python.org/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/python.svg', 'Python'),
(73, 'DEVELOPMENT', 'https://www.oracle.com/java/technologies/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/openjdk.svg', 'Java JDK'),
(74, 'DEVELOPMENT', 'https://go.dev/dl/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/go.svg', 'Go'),
(75, 'DEVELOPMENT', 'https://www.rust-lang.org/tools/install', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/rust.svg', 'Rust'),
(76, 'DEVELOPMENT', 'https://www.php.net/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/php.svg', 'PHP'),
(77, 'DEVELOPMENT', 'https://www.ruby-lang.org/en/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/ruby.svg', 'Ruby'),
(78, 'DEVELOPMENT', 'https://classic.yarnpkg.com/en/docs/install', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/yarn.svg', 'Yarn'),
(79, 'DEVELOPMENT', 'https://neovim.io/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/neovim.svg', 'Neovim'),
(80, 'DEVELOPMENT', 'https://dev.mysql.com/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/mysql.svg', 'MySQL'),
(81, 'DEVELOPMENT', 'https://www.postgresql.org/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/postgresql.svg', 'PostgreSQL'),
(82, 'DEVELOPMENT', 'https://www.mongodb.com/try/download/community', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/mongodb.svg', 'MongoDB'),
(83, 'DEVELOPMENT', 'https://redis.io/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/redis.svg', 'Redis'),
(84, 'DEVELOPMENT', 'https://developer.hashicorp.com/terraform/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/terraform.svg', 'Terraform'),
(85, 'DEVELOPMENT', 'https://www.jenkins.io/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/jenkins.svg', 'Jenkins'),
(86, 'PRODUCTIVITY', 'https://www.office.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/microsoftoffice.svg', 'Microsoft 365'),
(87, 'PRODUCTIVITY', 'https://www.libreoffice.org/download/download-libreoffice/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/libreoffice.svg', 'LibreOffice'),
(88, 'PRODUCTIVITY', 'https://1password.com/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/1password.svg', '1Password'),
(89, 'PRODUCTIVITY', 'https://bitwarden.com/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/bitwarden.svg', 'Bitwarden'),
(90, 'PRODUCTIVITY', 'https://obsidian.md/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/obsidian.svg', 'Obsidian'),
(91, 'PRODUCTIVITY', 'https://www.skype.com/get-skype/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/skype.svg', 'Skype'),
(92, 'PRODUCTIVITY', 'https://signal.org/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/signal.svg', 'Signal'),
(93, 'PRODUCTIVITY', 'https://telegram.org/apps', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/telegram.svg', 'Telegram'),
(94, 'PRODUCTIVITY', 'https://www.whatsapp.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/whatsapp.svg', 'WhatsApp'),
(96, 'DESIGN', 'https://www.adobe.com/products/indesign.html', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/adobeindesign.svg', 'Adobe InDesign'),
(97, 'DESIGN', 'https://www.adobe.com/products/photoshop-lightroom.html', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/adobelightroom.svg', 'Adobe Lightroom'),
(98, 'DESIGN', 'https://www.blackmagicdesign.com/products/davinciresolve/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/davinciresolve.svg', 'DaVinci Resolve'),
(99, 'DESIGN', 'https://affinity.serif.com/en-us/designer/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/affinitydesigner.svg', 'Affinity Designer'),
(100, 'DESIGN', 'https://affinity.serif.com/en-us/photo/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/affinityphoto.svg', 'Affinity Photo'),
(101, 'DESIGN', 'https://www.framer.com/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/framer.svg', 'Framer'),
(102, 'DESIGN', 'https://www.adobe.com/products/xd.html', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/adobexd.svg', 'Adobe XD'),
(103, 'MUSIC', 'https://www.ableton.com/en/live/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/abletonlive.svg', 'Ableton Live'),
(106, 'MUSIC', 'https://www.bandlab.com/products/cakewalk', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/bandlab.svg', 'Cakewalk'),
(108, 'ENTERTAINMENT', 'https://www.tiktok.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/tiktok.svg', 'TikTok'),
(109, 'ENTERTAINMENT', 'https://vimeo.com/upgrade', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/vimeo.svg', 'Vimeo'),
(111, 'ENTERTAINMENT', 'https://www.paramountplus.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/paramountplus.svg', 'Paramount+'),
(112, 'ENTERTAINMENT', 'https://www.stremio.com/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/stremio.svg', 'Stremio'),
(113, 'ENTERTAINMENT', 'https://www.redditinc.com/press', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/reddit.svg', 'Reddit'),
(114, 'ENTERTAINMENT', 'https://www.crunchyroll.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/crunchyroll.svg', 'Crunchyroll'),
(115, 'GAME', 'https://www.ea.com/ea-app', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/ea.svg', 'EA App'),
(116, 'GAME', 'https://ubisoftconnect.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/ubisoft.svg', 'Ubisoft Connect'),
(118, 'GAME', 'https://www.dota2.com/home', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/dota2.svg', 'Dota 2'),
(122, 'GAME', 'https://www.rockstargames.com/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/rockstargames.svg', 'Rockstar Games Launcher'),
(124, 'GAME', 'https://www.riotgames.com/en', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/riotgames.svg', 'Riot Client'),
(125, 'DEVELOPMENT', 'https://kubernetes.io/docs/tasks/tools/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/kubernetes.svg', 'Kubernetes'),
(126, 'DEVELOPMENT', 'https://www.ansible.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/ansible.svg', 'Ansible'),
(127, 'DEVELOPMENT', 'https://docs.npmjs.com/downloading-and-installing-node-js-and-npm', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/npm.svg', 'NPM'),
(128, 'DEVELOPMENT', 'https://webpack.js.org/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/webpack.svg', 'Webpack'),
(129, 'DEVELOPMENT', 'https://react.dev/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/react.svg', 'React'),
(130, 'DEVELOPMENT', 'https://angular.io/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/angular.svg', 'Angular'),
(131, 'DEVELOPMENT', 'https://vuejs.org/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/vuedotjs.svg', 'Vue.js'),
(132, 'DEVELOPMENT', 'https://svelte.dev/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/svelte.svg', 'Svelte'),
(133, 'DEVELOPMENT', 'https://www.virtualbox.org/wiki/Downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/virtualbox.svg', 'VirtualBox'),
(134, 'DEVELOPMENT', 'https://www.vmware.com/go/downloadplayer', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/vmware.svg', 'VMware'),
(135, 'DEVELOPMENT', 'https://nginx.org/en/download.html', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/nginx.svg', 'NGINX'),
(136, 'PRODUCTIVITY', 'https://calendar.google.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/googlecalendar.svg', 'Google Calendar'),
(137, 'PRODUCTIVITY', 'https://www.microsoft.com/en-us/microsoft-365/outlook/outlook-for-business', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/microsoftoutlook.svg', 'Microsoft Outlook'),
(138, 'PRODUCTIVITY', 'https://www.atlassian.com/software/jira', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/jira.svg', 'Jira'),
(139, 'PRODUCTIVITY', 'https://www.atlassian.com/software/confluence', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/confluence.svg', 'Confluence'),
(140, 'PRODUCTIVITY', 'https://miro.com/apps/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/miro.svg', 'Miro'),
(141, 'PRODUCTIVITY', 'https://www.teamviewer.com/en/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/teamviewer.svg', 'TeamViewer'),
(142, 'PRODUCTIVITY', 'https://keep.google.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/googlekeep.svg', 'Google Keep'),
(143, 'DESIGN', 'https://www.invisionapp.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/invision.svg', 'InVision'),
(144, 'DESIGN', 'https://proto.io/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/protoio.svg', 'Proto.io'),
(145, 'DESIGN', 'https://www.coreldraw.com/en/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/coreldraw.svg', 'CorelDRAW'),
(147, 'DESIGN', 'https://www.autodesk.com/products/maya/overview', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/autodeskmaya.svg', 'Autodesk Maya'),
(148, 'DESIGN', 'https://www.maxon.net/en/cinema-4d', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/cinema4d.svg', 'Cinema 4D'),
(149, 'MUSIC', 'https://www.winamp.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/winamp.svg', 'Winamp'),
(153, 'ENTERTAINMENT', 'https://x.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/x.svg', 'X'),
(154, 'ENTERTAINMENT', 'https://www.instagram.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/instagram.svg', 'Instagram'),
(155, 'ENTERTAINMENT', 'https://www.facebook.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/facebook.svg', 'Facebook'),
(156, 'ENTERTAINMENT', 'https://www.pinterest.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/pinterest.svg', 'Pinterest'),
(157, 'ENTERTAINMENT', 'https://www.imdb.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/imdb.svg', 'IMDb'),
(158, 'ENTERTAINMENT', 'https://letterboxd.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/letterboxd.svg', 'Letterboxd'),
(159, 'ENTERTAINMENT', 'https://www.goodreads.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/goodreads.svg', 'Goodreads'),
(160, 'GAME', 'https://godotengine.org/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/godotengine.svg', 'Godot Engine'),
(161, 'GAME', 'https://itch.io/app', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/itchdotio.svg', 'itch.io'),
(164, 'GAME', 'https://osu.ppy.sh/home/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/osu.svg', 'osu!'),
(165, 'DEVELOPMENT', 'https://dotnet.microsoft.com/en-us/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/dotnet.svg', '.NET'),
(166, 'DEVELOPMENT', 'https://kotlinlang.org/docs/command-line.html', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/kotlin.svg', 'Kotlin'),
(167, 'DEVELOPMENT', 'https://www.swift.org/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/swift.svg', 'Swift'),
(168, 'DEVELOPMENT', 'https://www.typescriptlang.org/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/typescript.svg', 'TypeScript'),
(169, 'DEVELOPMENT', 'https://atom.io/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/atom.svg', 'Atom'),
(170, 'DEVELOPMENT', 'https://dbeaver.io/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/dbeaver.svg', 'DBeaver'),
(171, 'DEVELOPMENT', 'https://www.vagrantup.com/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/vagrant.svg', 'Vagrant'),
(172, 'DEVELOPMENT', 'https://www.gitkraken.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/gitkraken.svg', 'GitKraken'),
(173, 'DEVELOPMENT', 'https://about.gitlab.com/install/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/gitlab.svg', 'GitLab'),
(174, 'DEVELOPMENT', 'https://bitbucket.org/product/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/bitbucket.svg', 'Bitbucket'),
(175, 'DEVELOPMENT', 'https://httpd.apache.org/download.cgi', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/apache.svg', 'Apache HTTP Server'),
(176, 'PRODUCTIVITY', 'https://www.google.com/chrome/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/googlechrome.svg', 'Google Chrome'),
(177, 'PRODUCTIVITY', 'https://www.mozilla.org/firefox/new/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/firefox.svg', 'Firefox Browser'),
(178, 'PRODUCTIVITY', 'https://brave.com/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/brave.svg', 'Brave'),
(179, 'PRODUCTIVITY', 'https://www.microsoft.com/edge', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/microsoftedge.svg', 'Microsoft Edge'),
(180, 'PRODUCTIVITY', 'https://www.microsoft.com/en-us/microsoft-365/excel', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/microsoftexcel.svg', 'Microsoft Excel'),
(181, 'PRODUCTIVITY', 'https://www.microsoft.com/en-us/microsoft-365/word', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/microsoftword.svg', 'Microsoft Word'),
(182, 'PRODUCTIVITY', 'https://www.thunderbird.net/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/thunderbird.svg', 'Mozilla Thunderbird'),
(183, 'PRODUCTIVITY', 'https://proton.me/mail/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/protonmail.svg', 'Proton Mail'),
(184, 'DESIGN', 'https://www.adobe.com/acrobat/pdf-reader.html', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/adobeacrobatreader.svg', 'Adobe Acrobat Reader'),
(185, 'DESIGN', 'https://penpot.app/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/penpot.svg', 'Penpot'),
(186, 'DESIGN', 'https://www.aseprite.org/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/aseprite.svg', 'Aseprite'),
(187, 'MUSIC', 'https://www.apple.com/itunes/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/itunes.svg', 'iTunes'),
(188, 'MUSIC', 'https://www.mixcloud.com/mobile/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/mixcloud.svg', 'Mixcloud'),
(189, 'MUSIC', 'https://bandcamp.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/bandcamp.svg', 'Bandcamp'),
(190, 'MUSIC', 'https://www.shazam.com/apps', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/shazam.svg', 'Shazam'),
(191, 'ENTERTAINMENT', 'https://9gag.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/9gag.svg', '9GAG'),
(192, 'ENTERTAINMENT', 'https://www.deviantart.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/deviantart.svg', 'DeviantArt'),
(193, 'ENTERTAINMENT', 'https://www.audible.com/ep/apps', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/audible.svg', 'Audible'),
(194, 'GAME', 'https://www.nintendo.com/switch/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/nintendoswitch.svg', 'Nintendo'),
(195, 'GAME', 'https://www.playstation.com/en-us/ps-app/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/playstation.svg', 'PlayStation'),
(196, 'GAME', 'https://www.xbox.com/en-US/apps/xbox-app-for-pc', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/xbox.svg', 'Xbox'),
(197, 'GAME', 'https://www.humblebundle.com/app', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/humblebundle.svg', 'Humble Bundle'),
(198, 'GAME', 'https://www.origin.com/usa/en-us/store/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/origin.svg', 'Origin'),
(199, 'GAME', 'https://www.nvidia.com/en-us/geforce-now/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/nvidia.svg', 'GeForce NOW'),
(200, 'DEVELOPMENT', 'https://www.sqlite.org/download.html', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/sqlite.svg', 'SQLite'),
(201, 'DEVELOPMENT', 'https://mariadb.org/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/mariadb.svg', 'MariaDB'),
(202, 'DEVELOPMENT', 'https://maven.apache.org/download.cgi', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/apachemaven.svg', 'Apache Maven'),
(203, 'DEVELOPMENT', 'https://gradle.org/install/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/gradle.svg', 'Gradle'),
(204, 'DEVELOPMENT', 'https://jupyter.org/install', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/jupyter.svg', 'Jupyter'),
(205, 'DEVELOPMENT', 'https://nextjs.org/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/nextdotjs.svg', 'Next.js'),
(206, 'DEVELOPMENT', 'https://vitejs.dev/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/vite.svg', 'Vite'),
(207, 'DEVELOPMENT', 'https://www.qt.io/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/qt.svg', 'Qt'),
(208, 'DEVELOPMENT', 'https://isocpp.org/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/cplusplus.svg', 'C++'),
(209, 'DEVELOPMENT', 'https://dotnet.microsoft.com/en-us/languages/csharp', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/csharp.svg', 'C#'),
(210, 'PRODUCTIVITY', 'https://www.google.com/docs/about/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/googledocs.svg', 'Google Docs'),
(211, 'PRODUCTIVITY', 'https://www.google.com/sheets/about/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/googlesheets.svg', 'Google Sheets'),
(212, 'PRODUCTIVITY', 'https://www.microsoft.com/en-us/microsoft-365/powerpoint', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/microsoftpowerpoint.svg', 'Microsoft PowerPoint'),
(214, 'PRODUCTIVITY', 'https://joplinapp.org/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/joplin.svg', 'Joplin'),
(216, 'PRODUCTIVITY', 'https://www.qbittorrent.org/download.php', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/qbittorrent.svg', 'qBittorrent'),
(218, 'DESIGN', 'https://affinity.serif.com/en-us/publisher/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/affinitypublisher.svg', 'Affinity Publisher'),
(219, 'DESIGN', 'https://marvelapp.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/marvelapp.svg', 'Marvel'),
(221, 'MUSIC', 'https://www.last.fm/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/lastdotfm.svg', 'Last.fm'),
(222, 'MUSIC', 'https://tunein.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/tunein.svg', 'TuneIn'),
(223, 'MUSIC', 'https://www.iheart.com/apps/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/iheartradio.svg', 'iHeartRadio'),
(225, 'ENTERTAINMENT', 'https://medium.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/medium.svg', 'Medium'),
(226, 'ENTERTAINMENT', 'https://getpocket.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/pocket.svg', 'Pocket'),
(227, 'ENTERTAINMENT', 'https://feedly.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/feedly.svg', 'Feedly'),
(228, 'ENTERTAINMENT', 'https://imgur.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/imgur.svg', 'Imgur'),
(229, 'ENTERTAINMENT', 'https://www.tumblr.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/tumblr.svg', 'Tumblr'),
(230, 'GAME', 'https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/counterstrike.svg', 'Counter-Strike 2'),
(235, 'DEVELOPMENT', 'https://www.jetbrains.com/rider/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/rider.svg', 'JetBrains Rider'),
(236, 'DEVELOPMENT', 'https://www.jetbrains.com/webstorm/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/webstorm.svg', 'WebStorm'),
(237, 'DEVELOPMENT', 'https://www.jetbrains.com/go/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/goland.svg', 'GoLand'),
(238, 'DEVELOPMENT', 'https://www.jetbrains.com/phpstorm/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/phpstorm.svg', 'PhpStorm'),
(239, 'DEVELOPMENT', 'https://sass-lang.com/install', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/sass.svg', 'Sass'),
(240, 'DEVELOPMENT', 'https://getbootstrap.com/docs/5.3/getting-started/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/bootstrap.svg', 'Bootstrap'),
(241, 'DEVELOPMENT', 'https://tailwindcss.com/docs/installation', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/tailwindcss.svg', 'Tailwind CSS'),
(242, 'DEVELOPMENT', 'https://jquery.com/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/jquery.svg', 'jQuery'),
(243, 'DEVELOPMENT', 'https://vercel.com/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/vercel.svg', 'Vercel'),
(244, 'DEVELOPMENT', 'https://www.netlify.com/products/cli/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/netlify.svg', 'Netlify'),
(245, 'DEVELOPMENT', 'https://www.docker.com/products/docker-hub', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/docker.svg', 'Docker Hub'),
(246, 'PRODUCTIVITY', 'https://powerbi.microsoft.com/en-us/downloads/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/powerbi.svg', 'Microsoft Power BI'),
(247, 'PRODUCTIVITY', 'https://www.microsoft.com/en-us/microsoft-365/onedrive/download', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/microsoftonedrive.svg', 'Microsoft OneDrive'),
(248, 'PRODUCTIVITY', 'https://www.google.com/chat/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/googlechat.svg', 'Google Chat'),
(249, 'PRODUCTIVITY', 'https://www.airtable.com/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/airtable.svg', 'Airtable'),
(250, 'PRODUCTIVITY', 'https://zapier.com/apps', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/zapier.svg', 'Zapier'),
(251, 'PRODUCTIVITY', 'https://ifttt.com/apps', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/ifttt.svg', 'IFTTT'),
(253, 'PRODUCTIVITY', 'https://www.vim.org/download.php', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/vim.svg', 'Vim'),
(254, 'PRODUCTIVITY', 'https://openoffice.apache.org/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/apacheopenoffice.svg', 'Apache OpenOffice'),
(255, 'DESIGN', 'https://dribbble.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/dribbble.svg', 'Dribbble'),
(256, 'DESIGN', 'https://www.behance.net/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/behance.svg', 'Behance'),
(257, 'DESIGN', 'https://www.pixiv.net/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/pixiv.svg', 'Pixiv'),
(258, 'DESIGN', 'https://www.artstation.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/artstation.svg', 'ArtStation'),
(259, 'DESIGN', 'https://prezi.com/desktop/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/prezi.svg', 'Prezi'),
(262, 'ENTERTAINMENT', 'https://www.linkedin.com/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/linkedin.svg', 'LinkedIn'),
(263, 'ENTERTAINMENT', 'https://www.snapchat.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/snapchat.svg', 'Snapchat'),
(264, 'ENTERTAINMENT', 'https://www.rottentomatoes.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/rottentomatoes.svg', 'Rotten Tomatoes'),
(372, 'DEVELOPMENT', 'https://www.arduino.cc/en/software', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/arduino.svg', 'Arduino'),
(373, 'DEVELOPMENT', 'https://grafana.com/get/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/grafana.svg', 'Grafana'),
(374, 'DEVELOPMENT', 'https://prometheus.io/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/prometheus.svg', 'Prometheus'),
(375, 'DEVELOPMENT', 'https://www.raspberrypi.com/software/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/raspberrypi.svg', 'Raspberry Pi OS'),
(378, 'DEVELOPMENT', 'https://cmake.org/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/cmake.svg', 'CMake'),
(379, 'PRODUCTIVITY', 'https://www.zotero.org/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/zotero.svg', 'Zotero'),
(380, 'PRODUCTIVITY', 'https://tutanota.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/tutanota.svg', 'Tutanota'),
(381, 'PRODUCTIVITY', 'https://www.mendeley.com/download-desktop-new/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/mendeley.svg', 'Mendeley'),
(382, 'PRODUCTIVITY', 'https://anydesk.com/en/downloads', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/anydesk.svg', 'AnyDesk'),
(383, 'PRODUCTIVITY', 'https://www.citrix.com/downloads/workspace-app/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/citrix.svg', 'Citrix Workspace'),
(384, 'PRODUCTIVITY', 'https://www.autohotkey.com/download/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/autohotkey.svg', 'AutoHotkey'),
(386, 'DESIGN', 'https://www.squarespace.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/squarespace.svg', 'Squarespace'),
(387, 'DESIGN', 'https://www.wix.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/wix.svg', 'Wix'),
(388, 'DESIGN', 'https://wordpress.com/create/?aff=58022', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/wordpress.svg', 'WordPress'),
(389, 'DESIGN', 'https://www.freecad.org/downloads.php', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/freecad.svg', 'FreeCAD'),
(390, 'ENTERTAINMENT', 'https://www.duolingo.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/duolingo.svg', 'Duolingo'),
(391, 'ENTERTAINMENT', 'https://www.ted.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/ted.svg', 'TED'),
(392, 'ENTERTAINMENT', 'https://www.wattpad.com/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/wattpad.svg', 'Wattpad'),
(393, 'ENTERTAINMENT', 'https://www.wikipedia.org/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/wikipedia.svg', 'Wikipedia'),
(397, 'GAME', 'https://www.pokemon.com/us/pokemon-video-games/pokemon-unite/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/pokemon.svg', 'Pokémon'),
(398, 'GAME', 'https://www.playstation.com/en-gb/ps5/', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/playstation5.svg', 'PlayStation 5'),
(399, 'GAME', 'https://www.roblox.com/create', 'https://cdn.jsdelivr.net/npm/simple-icons/icons/robloxstudio.svg', 'Roblox Studio');

